database:
  data_source: "sqlite3:///data/buildbuddy.db"
storage:
  ttl_seconds: 2592000  # 30 days
  chunk_file_size_bytes: 3000000  # 3 MB
  disk:
    root_directory: /data/buildbuddy/
cache:
  max_size_bytes: 1000000000  # 1 GB
  #in_memory: true
  disk:
    root_directory: /data/buildbuddy/buildbuddy_cache
